config/routes.rb
Kikniela::Application.routes.draw do
	
	devise_for :users, :controllers => { :sessions => "json_sessions" }

	devise_for :admin_users, ActiveAdmin::Devise.config
	
	
	ActiveAdmin.routes(self)

	namespace :api do
		namespace :v1 do
			resources :games
			resources :bets
			resources :users
		end
	end

	
	
	
	root :to => "home#index"
	
	get '*path', to: 'home#index'
	
	

	

	
end

app/models/bet.rb
class Bet < ActiveRecord::Base
  belongs_to :user
  belongs_to :game
end

app/controllers/api/v1/bets_controller.rb
class Api::V1::BetsController < ApplicationController
	before_filter :authenticate_user!
	respond_to :json

  def index
    #respond_with Bet.all
		@bets = Bet.all
		respond_to do |format|
			format.html { render html: @bets }
			format.json { render json: @bets }
		end
  end

  def show
    respond_with bet
  end

  def create
    #respond_with :api, :v1, Bet.create(bet_params)
		@bet = Bet.new(bet_params)
		respond_to do |format|
			if @bet.save
				format.html { redirect_to @bet, notice: 'Post was successfully created.' }
				format.json { render json: @bet }
			else
				format.html { render action: 'new' }
				format.json { render json: @bet.errors, status: :unprocessable_entity }
			end
		end
  end

  def update
    respond_with bet.update(bet_params)
  end

  def destroy
    respond_with bet.destroy
  end

  private

  def bet
    Bet.find(params[:id])
  end

  def bet_params
    params.require(:bet).permit(:week, :tip, :hit, :game_id, :user_id, :updated_at)
  end

end

app/controllers/bets_controller.rb
class BetsController < InheritedResources::Base
	#before_filter :authenticate_user!#, except: [:index, :show]
end

app/helpers/bets_helper.rb
module BetsHelper
  def options_for_tip
  [
    ['1', '1'],
    ['X', 'X'],
    ['2', '2']
  ]
  end	
end

app/views/bets/_form.html.erb
<%= form_for(@bet) do |f| %>
  <% if @bet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bet.errors.count, "error") %> prohibited this bet from being saved:</h2>

      <ul>
      <% @bet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
		<%= f.select :user, User.all.map {|f| f.name} %>
  </div>
  <div class="field">
    <%= f.label :game_id %><br>
    <%= f.select :game_id, Game.all.map {|f| f.id} %>
  </div>
  <div class="field">
    <%= f.label :week %><br>
    <%= f.number_field :week %>
  </div>
  <div class="field">
    <%= f.label :hit %><br>
    <%= f.number_field :hit %>
  </div>
  <div class="field">
    <%= f.label :tip %><br>
    <%= f.number_field :tip %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bets/edit.html.erb
<h1>Editing bet</h1>

<%= render 'form' %>

<%= link_to 'Show', @bet %> |
<%= link_to 'Back', bets_path %>

app/views/bets/index.html.erb
<h1>Listing bets</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Game</th>
      <th>Week</th>
      <th>Hit</th>
      <th>Tip</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @bets.each do |bet| %>
      <tr>
        <td><%= bet.user %></td>
        <td><%= bet.game %></td>
        <td><%= bet.week %></td>
        <td><%= bet.hit %></td>
        <td><%= bet.tip %></td>
        <td><%= link_to 'Show', bet %></td>
        <td><%= link_to 'Edit', edit_bet_path(bet) %></td>
        <td><%= link_to 'Destroy', bet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bet', new_bet_path %>

app/views/bets/new.html.erb
<h1>New bet</h1>

<%= render 'form' %>

<%= link_to 'Back', bets_path %>

app/views/bets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @bet.user %>
</p>

<p>
  <strong>Game:</strong>
  <%= @bet.game %>
</p>

<p>
  <strong>Week:</strong>
  <%= @bet.week %>
</p>

<p>
  <strong>Hit:</strong>
  <%= @bet.hit %>
</p>

<p>
  <strong>Tip:</strong>
  <%= @bet.tip %>
</p>

<%= link_to 'Edit', edit_bet_path(@bet) %> |
<%= link_to 'Back', bets_path %>